### ISSUE TITLE
Check author info

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss-probprog#6]
Here's what we currently have:
> Authors’ addresses: Chad Scherrer, RelationalAI, Seattle, WA, chad.scherrer@gmail.com; Taine Zhao, University of Tsukuba, Department of Computer Science.

This is fine with me; if you like you could add a city and/or email

**Comment by thautwarm** [comment]
I'd like to add this email: thaut@logic.cs.tsukuba.ac.jp
